### ISSUE TITLE
Transparent plot for `2^x`

### ISSUE THREAD

**Issue by amejiarosario** [maurizzzio/function-plot#83]
Transparent plot for `2^x`
```javascript
{ fn: '2^x'}, 
```

I tried defining a color but not luck. Looks like a bug or there's another alternative?

![plot-2 x](https://cloud.githubusercontent.com/assets/418605/19831008/e9c7da84-9dcd-11e6-8583-9553f8745e07.gif)

http://codepen.io/amejiarosario/pen/QKXyQE?editors=1010

**Comment by maurizzzio** [comment]
thanks for the report!

**Comment by maurizzzio** [comment]
Thanks for the report!

**Comment by maurizzzio** [comment]
Should be fixed in v1.17.3 (note that the `pow` function for intervals is defined only when the exponent is a single real number, not an interval, for this specific function you should use the builtIn sampler instead) e.g.

```js
functionPlot({
  target: '#demo',
  data: [
    { fn: '2^x', sampler: 'builtIn', graphType: 'polyline' }
  ]
});
```

**Comment by amejiarosario** [comment]
cool, I just test it out from the dist folder and it works :)

**Comment by belph** [comment]
@maurizzzio: It seems that this is still not fixed. I have the same issue after checking out the copy from `master` in `dist`, and I still see the issue on the demo on the website.

**Comment by maurizzzio** [comment]
@belph I just tried the following on the jsbin embed on the website and is working

```js
functionPlot({
  target: '#demo',
  data: [
    { fn: '2^x', sampler: 'builtIn', graphType: 'polyline' }
  ]
})
```

**Comment by amejiarosario** [comment]
@belph you can see a working version on my codepen: http://codepen.io/amejiarosario/pen/QKXyQE

This are the libs I used: 
![image](https://cloud.githubusercontent.com/assets/418605/20760649/98a706f4-b6ee-11e6-8c4b-ce07d8d2ba2a.png)

**Comment by belph** [comment]
Ah, my mistake! I overlooked the additional properties in @maurizzzio's comment. After adding the `graphType:'polyline'` property, everything renders as expected.
